### ISSUE TITLE
Not Able to run the application

### ISSUE THREAD

**Issue by Vswaroop04** [JoRDaV1/Digicerti#2]
Facing this weird error

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\divye\OneDrive\Documents\DigiCerti\frontend\node_modules\webpack\lib\util\createHash.js:90:53)
    at NormalModule._initBuildHash (C:\Users\divye\OneDrive\Documents\DigiCerti\frontend\node_modules\webpack\lib\NormalModule.js:386:16)
    at C:\Users\divye\OneDrive\Documents\DigiCerti\frontend\node_modules\webpack\lib\NormalModule.js:418:10
    at C:\Users\divye\OneDrive\Documents\DigiCerti\frontend\node_modules\webpack\lib\NormalModule.js:293:13
    at C:\Users\divye\OneDrive\Documents\DigiCerti\frontend\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\divye\OneDrive\Documents\DigiCerti\frontend\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\Users\divye\OneDrive\Documents\DigiCerti\frontend\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\Users\divye\OneDrive\Documents\DigiCerti\frontend\node_modules\react-scripts\node_modules\babel-loader\lib\index.js:51:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.16.0

**Comment by Vswaroop04** [comment]
This is resolved in this commit [dc92a8f8dba97665b6d242869c0b5a8242c544e4](https://github.com/JoRDaV1/Digicerti/commit/dc92a8f8dba97665b6d242869c0b5a8242c544e4)
